# docker/nginx/default.conf

upstream php_servers {
    # 'saas' սերվիսի անունն է docker-compose-ում:
    # Nginx-ը ավտոմատ կբաշխի հարցումները բոլոր աշխատող կոնտեյներների միջև:
    server saas:9000;
}

server {
    listen 80;
    index index.php index.html;
    server_name localhost saas.local; # Ավելացրեք ձեր տիրույթի անունը (domain)

    root /var/www/public; # Laravel-ի համար կարևոր է նշել public թղթապանակը

    # Լոգերի կարգավորում (ցույց կտա, թե որ կոնտեյներին գնաց հարցումը)
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # PHP-FPM հարցումների մշակում
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # Օգտագործում ենք վերևում սահմանված upstream-ը
        fastcgi_pass php_servers;

        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Անվտանգության և արագագործության լրացուցիչ կարգավորումներ
        fastcgi_read_timeout 300;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }

    # Արգելել մուտքը .ht ֆայլերին
    location ~ /\.ht {
        deny all;
    }
}
