name: Laravel Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/saas

            echo "Pull latest changes"
            git pull origin master

            echo "Install node modules"
            npm install

#            echo "Build frontend"
#            npm run build

            echo "Run frontend"
            npm run dev

            echo "Restart docker containers"
#            docker compose down
            docker compose up -d --build

            echo "Laravel clear cache"
            docker compose exec -T saas php artisan optimize:clear

            echo "Run migrations"
            docker compose exec -T saas php artisan migrate --force

            echo "Restart queue"
            docker compose exec -T saas php artisan queue:restart

            echo "Restart reverb"
            docker compose exec -T saas php artisan reverb:start

            echo "Deploy finished"
